(function () {
  var I18N = {
    'nav.login': { tr: 'Giriş yap', en: 'Log in' },
    'nav.register': { tr: 'Kayıt ol', en: 'Sign up' },
    'nav.lang': { tr: 'EN', en: 'TR' },
    'hero.badge': { tr: '✦ Trader\'lar için hepsi bir arada platform', en: '✦ The all-in-one platform for traders' },
    'hero.h2': { tr: 'Öğren, uygula,<br><span class="grad">disiplinini koru.</span>', en: 'Learn, practice,<br><span class="grad">stay disciplined.</span>' },
    'hero.p': { tr: 'Video eğitim, trade defteri, onchain veriler, indikatörler ve trader topluluğu — bir trader\'ın ihtiyacı olan her şey tek çatı altında.', en: 'Video courses, trade journal, on-chain data, indicators and a trader community — everything a trader needs under one roof.' },
    'hero.register': { tr: 'Ücretsiz başla →', en: 'Start free →' },
    'hero.proof.txt': { tr: 'kayıtlı trader disiplinle işlem yapıyor', en: 'registered traders trading with discipline' },
    'hero.proof.rating': { tr: 'topluluk puanı', en: 'community rating' },
    'hero.live.online': { tr: 'kişi şu an çevrimiçi', en: 'people online now' },
    'hero.live.total': { tr: 'toplam ziyaret', en: 'total visits' },
    'hero.live.members': { tr: 'kayıtlı üye', en: 'registered members' },
    'hsw.cur': { tr: 'Kümülatif R', en: 'Cumulative R' },
    'hsw.wr': { tr: 'Win Rate', en: 'Win Rate' },
    'hsw.best': { tr: 'En iyi ay', en: 'Best month' },
    'hsw.year': { tr: '▲ bu yıl', en: '▲ this year' },
    'hsw.trades': { tr: '148 işlem', en: '148 trades' },
    'hsw.month': { tr: 'Haziran', en: 'June' },
    'hsw.recent': { tr: 'Son İşlemler', en: 'Recent Trades' },
    'sec.features.eyebrow': { tr: 'Neler var?', en: 'What\'s inside?' },
    'sec.features.h': { tr: 'Bir trader\'ın ihtiyacı olan her şey', en: 'Everything a trader needs' },
    'sec.features.p': { tr: 'Eğitimden analize, defterden topluluğa — hepsi tek platformda.', en: 'From education to analysis, journal to community — all in one platform.' },
    'feat.check': { tr: 'Check List', en: 'Check List' },
    'feat.check.d': { tr: 'Kriterleri işaretle, setup kalite skorunu ve A+ / B kararını anında gör.', en: 'Tick the criteria and instantly see your setup quality score and the A+ / B decision.' },
    'feat.journal': { tr: 'Trade Günlüğü', en: 'Trade Journal' },
    'feat.journal.d': { tr: 'Her işlemi R cinsinden kaydet, kümülatif eğriyi ve istatistiklerini izle.', en: 'Log every trade in R, track your cumulative curve and statistics.' },
    'feat.weekly': { tr: 'Haftalık Değerlendirme', en: 'Weekly Review' },
    'feat.weekly.d': { tr: 'Haftalık RR ve retrospektif ile performans trendini takip et.', en: 'Track your performance trend with weekly RR and retrospective.' },
    'feat.onchain': { tr: 'Onchain', en: 'Onchain' },
    'feat.onchain.d': { tr: 'Funding, CVD ve akış verileriyle piyasanın konumunu oku.', en: 'Read the market\'s position with funding, CVD and flow data.' },
    'feat.calc': { tr: 'Alfa Calculator', en: 'Alfa Calculator' },
    'feat.calc.d': { tr: 'Riske göre pozisyon boyutunu ve kaldıracı hızlıca hesapla.', en: 'Quickly calculate position size and leverage based on risk.' },
    'feat.trading': { tr: 'Trading', en: 'Trading' },
    'feat.trading.d': { tr: 'Canlı grafik, indikatörler ve watchlist tek panelde.', en: 'Live charts, indicators and watchlist in one panel.' },
    'feat.edu': { tr: 'Alfa Edu', en: 'Alfa Edu' },
    'feat.edu.d': { tr: 'Bölüm → konu → video; teknikten psikolojiye ücretsiz eğitim.', en: 'Section → topic → video; free education from technicals to psychology.' },
    'feat.indicators': { tr: 'İndikatörler', en: 'Indicators' },
    'feat.indicators.d': { tr: 'Aggr, Alfa Levels, Flow — kendi indikatör setini kur.', en: 'Aggr, Alfa Levels, Flow — build your own indicator set.' },
    'feat.calendar': { tr: 'Ekonomik Takvim', en: 'Economic Calendar' },
    'feat.calendar.d': { tr: '3 yıldız makro veriler ve piyasayı etkileyen haberler.', en: '3-star macro data and market-moving news.' },
    'feat.magazine': { tr: 'Dergi', en: 'Magazine' },
    'feat.magazine.d': { tr: 'Haftalık piyasa analizleri ve trade notları tek yerde.', en: 'Weekly market analyses and trade notes in one place.' },
    'feat.alfa': { tr: 'Alfa Ol', en: 'Become Alfa' },
    'feat.alfa.d': { tr: 'Topluluk akışı, PnL performansı ve referansla katılım.', en: 'Community feed, PnL performance and joining by referral.' },
    'feat.support': { tr: 'Canlı Destek', en: 'Live Support' },
    'feat.support.d': { tr: 'İhtiyacın olduğunda anında yanıt veren destek hattı.', en: 'A support line that answers instantly when you need it.' },
    'feat.score': { tr: 'PUAN', en: 'SCORE' },
    'sec.reviews.eyebrow': { tr: 'Üye yorumları', en: 'Member reviews' },
    'sec.reviews.h': { tr: 'Üyeler ne diyor?', en: 'What do members say?' },
    'sec.reviews.p': { tr: 'Gerçek deneyimler, gerçek trader\'lar. Yorumunu yazarken ismini gösterebilir ya da anonim kalabilirsin — seçim senin.', en: 'Real experiences, real traders. When writing your review you can show your name or stay anonymous — your choice.' },
    'rv.per5': { tr: '/ 5', en: '/ 5' },
    'rv.count': { tr: 'yorum', en: 'reviews' },
    'rv.none': { tr: 'Henüz yorum yok', en: 'No reviews yet' },
    'rv.loading': { tr: 'Yorumlar yükleniyor…', en: 'Loading reviews…' },
    'rv.more': { tr: 'Daha fazla yorum gör ↓', en: 'Show more reviews ↓' },
    'rv.empty': { tr: 'Henüz yorum yok. İlk yorumu sen bırak!', en: 'No reviews yet. Be the first to leave one!' },
    'rv.form.h': { tr: '⭐ Websitesi Hakkında Yorum Yap', en: '⭐ Review the Website' },
    'rv.form.q': { tr: 'Siteyi beğendin mi? Deneyimin ne kadar iyiydi?', en: 'Did you like the site? How good was your experience?' },
    'rv.form.qGuest': { tr: 'Siteyi beğendin mi? Deneyimini paylaş, yeni trader\'lara yol göster.', en: 'Did you like the site? Share your experience and guide new traders.' },
    'rv.form.updateHead': { tr: 'Yorumunu güncelle', en: 'Update your review' },
    'rv.form.qEdit': { tr: 'Yorumunu düzenleyebilir ya da silebilirsin.', en: 'You can edit or delete your review.' },
    'rv.form.loginNote': { tr: 'Yorum yazmak için giriş yapman gerekiyor — saniyeler sürer. Girişten sonra adını/nick\'ini yazabilir ya da anonim kalabilirsin.', en: 'You need to log in to leave a review — it takes seconds. After logging in you can write your name/nick or stay anonymous.' },
    'rv.form.loginBtn': { tr: 'Giriş yap ve yorumunu bırak →', en: 'Log in and leave your review →' },
    'rv.form.update': { tr: 'Güncelle', en: 'Update' },
    'rv.form.publish': { tr: 'Yorumu yayınla', en: 'Publish review' },
    'rv.form.nameLbl': { tr: 'Adın / Nick\'in', en: 'Your name / Nick' },
    'rv.form.namePh': { tr: 'Anonim kalmak istersen boş bırak', en: 'Leave blank to stay anonymous' },
    'rv.form.anon': { tr: 'Anonim kal', en: 'Stay anonymous' },
    'rv.form.textPh': { tr: 'Deneyimini yaz — yeni trader\'lara yol göster…', en: 'Write about your experience — guide new traders…' },
    'rv.form.del': { tr: 'Sil', en: 'Delete' },
    'rv.member': { tr: 'Üye', en: 'Member' },
    'rv.form.delConfirm': { tr: 'Yorumunu silmek istediğine emin misin?', en: 'Are you sure you want to delete your review?' },
    'stats.tools': { tr: 'Araç & modül', en: 'Tools & modules' },
    'stats.quality': { tr: 'Kalite kararı', en: 'Quality decision' },
    'stats.sync': { tr: 'Otomatik senkron', en: 'Auto sync' },
    'stats.free': { tr: 'Cihazlar arası erişim', en: 'Cross-device access' },
    'comm.h': { tr: 'Bir fikrin mi var? Bize yardım etmek ister misin?', en: 'Got an idea? Want to help us?' },
    'comm.p': { tr: 'İstediğin özelliği söyle, düşüncelerini paylaş. Siteye yön veren topluluğa Telegram\'dan katıl, orada birebir konuşalım.', en: 'Tell us the feature you want, share your thoughts. Join the community that shapes the site on Telegram and let\'s talk one-on-one.' },
    'comm.btn': { tr: 'Telegram topluluğuna katıl', en: 'Join the Telegram community' },
    'cta.h': { tr: 'Bir sonraki işlemin daha disiplinli olsun', en: 'Make your next trade more disciplined' },
    'cta.p': { tr: 'Hesabını oluştur, defterin her cihazdan seninle olsun. Saniyeler sürer.', en: 'Create your account, keep your journal with you on every device. It takes seconds.' },
    'cta.btn': { tr: 'Ücretsiz kayıt ol', en: 'Sign up free' },
    'quote.p': { tr: 'Kazan ya da kaybet, herkes piyasadan istediğini alır.', en: 'Whether you win or lose, everyone gets what they want from the market.' },
    'quote.cite': { tr: '— Ed Seykota', en: '— Ed Seykota' },
    'foot': { tr: 'Alfa Traders · Alfa trader\'lar için disiplin aracı · Verilerin sana özel, hesabında güvende.', en: 'Alfa Traders · Discipline tool for Alfa traders · Your data is private and secure in your account.' },
    'auth.close': { tr: 'Kapat', en: 'Close' },
    'auth.name': { tr: 'İsim', en: 'Name' },
    'auth.namePh': { tr: 'Adın', en: 'Your name' },
    'auth.email': { tr: 'E-posta', en: 'E-mail' },
    'auth.pass': { tr: 'Şifre', en: 'Password' },
    'auth.passPh': { tr: 'En az 6 karakter', en: 'At least 6 characters' },
    'auth.remember': { tr: 'Beni hatırla', en: 'Remember me' },
    'auth.forgot': { tr: 'Şifreni mi unuttun?', en: 'Forgot your password?' },
    'auth.back': { tr: '← Girişe dön', en: '← Back to log in' },
    'edupub.free': { tr: 'Ücretsiz Erişim', en: 'Free Access' },
    'edupub.close': { tr: '✕ Kapat', en: '✕ Close' },
    'edupub.topics': { tr: 'Konular', en: 'Topics' },
    'edupub.empty': { tr: 'Bu bölümde henüz içerik yok.', en: 'No content in this section yet.' },
    'edupub.yt': { tr: 'YouTube\'da aç ↗', en: 'Open on YouTube ↗' },
    'edupub.videos': { tr: 'İçerik', en: 'Content' },
    'edupub.select': { tr: 'Soldan bir konu seç — videoları ve notları burada izle.', en: 'Select a topic on the left — watch the videos and notes here.' },
    'edupub.cta.h': { tr: 'Devam etmek için kayıt ol', en: 'Sign up to continue' },
    'edupub.cta.p': { tr: 'Not al, ilerleme takip et, kendi içerik önerilerini ekle ve tam platforma ücretsiz eriş.', en: 'Take notes, track progress, add your own content suggestions and get free access to the full platform.' },
    'edupub.cta.btn': { tr: 'Ücretsiz kayıt ol →', en: 'Sign up free →' },
    'app.home': { tr: '🏠 Ana Menü', en: '🏠 Home' },
    'app.trader': { tr: '⚡ Trader ▾', en: '⚡ Trader ▾' },
    'app.edu': { tr: '🎓 Edu ▾', en: '🎓 Edu ▾' },
    'app.news': { tr: '📰 AlfaNews ▾', en: '📰 AlfaNews ▾' },
    'app.check': { tr: '✅ Check List', en: '✅ Check List' },
    'app.journal': { tr: '📈 Trade Günlüğü', en: '📈 Trade Journal' },
    'app.onchain': { tr: '⛓️ Onchain', en: '⛓️ Onchain' },
    'app.calc': { tr: '🧮 Alfa Calculator', en: '🧮 Alfa Calculator' },
    'app.weekly': { tr: '📊 Haftalık Değerlendirme', en: '📊 Weekly Review' },
    'app.trading': { tr: '📉 Trading', en: '📉 Trading' },
    'app.eduPage': { tr: '🎓 Alfa Edu', en: '🎓 Alfa Edu' },
    'app.strategies': { tr: '🧪 Stratejiler', en: '🧪 Strategies' },
    'app.analiz': { tr: '🧭 Analiz Köşesi', en: '🧭 Analysis Corner' },
    'app.butce': { tr: '💰 Alfa Defter', en: '💰 Alfa Ledger' },
    'app.pano': { tr: '🛠️ Çalışma Panosu', en: '🛠️ Work Board' },
    'app.mentoring': { tr: '🤝 Mentoring', en: '🤝 Mentoring' },
    'app.indicators': { tr: '📐 İndikatörler', en: '📐 Indicators' },
    'app.designer': { tr: '🧬 Alfa Designer', en: '🧬 Alfa Designer' },
    'app.calendar': { tr: '📅 Ekonomik Takvim', en: '📅 Economic Calendar' },
    'app.magazine': { tr: '🗞️ Dergi', en: '🗞️ Magazine' },
    'app.alfa': { tr: '🚀 Alfa Ol', en: '🚀 Become Alfa' },
    'app.support': { tr: '💬 Canlı Destek', en: '💬 Live Support' },
    'app.contact': { tr: 'İletişim', en: 'Contact' },
    'app.live.online': { tr: 'çevrimiçi', en: 'online' },
    'app.live.total': { tr: 'ziyaret', en: 'visits' },
    'app.live.members': { tr: 'üye', en: 'members' },
    'app.logout': { tr: 'Çıkış', en: 'Log out' },
    'tv.searchPh': { tr: 'Sembol ara (BTC, XAU, ETH…)', en: 'Search symbol (BTC, XAU, ETH…)' },
    'tv.terminal': { tr: '📉 Trading Terminali', en: '📉 Trading Terminal' },
    'ticker.label': { tr: '📖 Günün Dersi', en: '📖 Lesson of the Day' },
    'ticker.loading': { tr: 'Yükleniyor...', en: 'Loading...' },
    'fab.b': { tr: 'Websitesi Hakkında', en: 'Rate the Website' },
    'fab.main': { tr: 'Yorum Yap', en: 'Leave a Review' },
    'act.edit': { tr: '✎ Düzenle', en: '✎ Edit' },
    'act.cancel': { tr: 'Vazgeç', en: 'Cancel' },
    'act.add': { tr: 'Ekle', en: 'Add' },
    'act.save': { tr: 'Kaydet', en: 'Save' },
    'act.send': { tr: 'Gönder', en: 'Send' },
    'flt.all': { tr: 'Tümü', en: 'All' },
    'flt.today': { tr: 'Bugün', en: 'Today' },
    'flt.week': { tr: 'Bu hafta', en: 'This week' },
    'flt.month': { tr: 'Bu ay', en: 'This month' },
    'pg.topics': { tr: 'Konular', en: 'Topics' },
    'pg.addTopic': { tr: '+ Konu', en: '+ Topic' },
    'pg.trading.t': { tr: 'Trading Terminali', en: 'Trading Terminal' },
    'pg.trading.s': { tr: 'Canlı grafik burada çalışır (giriş gerekmez). Hesabını/watchlist\'ini bağlamak için aşağıdaki butonla TradingView\'da giriş yap — aynı tarayıcıda girince widget otomatik tanır.', en: 'Live charts work here (no login required). To connect your account/watchlist, sign in to TradingView with the button below — once signed in on the same browser, the widget picks it up automatically.' },
    'pg.trading.loginTv': { tr: '🔑 TradingView\'a giriş', en: '🔑 Sign in to TradingView' },
    'pg.trading.openTv': { tr: 'TradingView\'da aç', en: 'Open on TradingView' },
    'pg.defter.t': { tr: 'Alfa-Check List', en: 'Alfa-Check List' },
    'pg.defter.s': { tr: 'Her işlem öncesi kriterleri puanla, kararını ver.', en: 'Score the criteria before every trade and make your decision.' },
    'pg.defter.aiT': { tr: '🧠 Yapay Zeka ile Kişisel Checklist', en: '🧠 Personal Checklist with AI' },
    'pg.defter.aiS': { tr: 'Profili doldur → öneri üret → checklist\'e uygula', en: 'Fill your profile → generate suggestions → apply to checklist' },
    'pg.defter.aiMkt': { tr: 'Piyasa', en: 'Market' },
    'pg.defter.aiMkt1': { tr: 'Kripto (Spot)', en: 'Crypto (Spot)' },
    'pg.defter.aiMkt2': { tr: 'Kripto (Futures)', en: 'Crypto (Futures)' },
    'pg.defter.aiMkt3': { tr: 'Altın (XAU)', en: 'Gold (XAU)' },
    'pg.defter.aiMkt4': { tr: 'Gümüş (XAG)', en: 'Silver (XAG)' },
    'pg.defter.aiMkt5': { tr: 'Dolar Endeksi (DXY)', en: 'Dollar Index (DXY)' },
    'pg.defter.aiMkt6': { tr: 'FX Majör (EUR/USD…)', en: 'FX Major (EUR/USD…)' },
    'pg.defter.aiMkt7': { tr: 'Endeksler (SPX / NASDAQ)', en: 'Indices (SPX / NASDAQ)' },
    'pg.defter.aiMkt8': { tr: 'Emtia (Petrol / Gaz…)', en: 'Commodities (Oil / Gas…)' },
    'pg.defter.aiExp': { tr: 'Deneyim', en: 'Experience' },
    'pg.defter.aiExp1': { tr: 'Yeni başlayan', en: 'Beginner' },
    'pg.defter.aiExp2': { tr: 'Orta', en: 'Intermediate' },
    'pg.defter.aiExp3': { tr: 'İleri', en: 'Advanced' },
    'pg.defter.aiStyle': { tr: 'Çalışma tarzı', en: 'Trading style' },
    'pg.defter.aiStyle1': { tr: 'Scalp (M1-M5)', en: 'Scalp (M1-M5)' },
    'pg.defter.aiStyle2': { tr: 'Gün içi (M15-H1)', en: 'Intraday (M15-H1)' },
    'pg.defter.aiStyle3': { tr: 'Swing (H4-Günlük)', en: 'Swing (H4-Daily)' },
    'pg.defter.aiStyle4': { tr: 'Karışık', en: 'Mixed' },
    'pg.defter.aiStratL': { tr: 'Strateji(ler)', en: 'Strategy(ies)' },
    'pg.defter.aiStratPh': { tr: 'Breaker, IFVG, Orderflow…', en: 'Breaker, IFVG, Orderflow…' },
    'pg.defter.aiLbl1': { tr: 'Kullandığın konsept / araçlar', en: 'Concepts / tools you use' },
    'pg.defter.aiLbl2': { tr: 'Duygusal zayıflıkların', en: 'Your emotional weaknesses' },
    'pg.defter.aiLbl3': { tr: 'Problemlerin — işaretle, AI dönütüne işler', en: 'Your problems — mark them, they feed into AI feedback' },
    'pg.defter.aiGen': { tr: '🤖 Öneri Üret', en: '🤖 Generate Suggestions' },
    'pg.defter.aiBan': { tr: '🧠 AI Profili aktif', en: '🧠 AI Profile active' },
    'pg.defter.aiExit': { tr: 'Kendi ayarlarıma dön', en: 'Back to my own settings' },
    'pg.defter.pairPh': { tr: 'PAIR ADI (ör. EUR)', en: 'PAIR NAME (e.g. EUR)' },
    'pg.defter.emoT': { tr: 'Duygusal Durum', en: 'Emotional State' },
    'pg.defter.lock': { tr: 'SİSTEM KİLİTLİ', en: 'SYSTEM LOCKED' },
    'pg.defter.sabah': { tr: 'Sabah bağlamı', en: 'Morning context' },
    'pg.defter.sabahPh': { tr: 'Piyasa nerede uyandı, gece ne oldu, bugünün ana hikâyesi ne?', en: 'Where did the market wake up, what happened overnight, what is today\'s main story?' },
    'pg.defter.verdict': { tr: 'ANLAŞMA YOK', en: 'NO AGREEMENT' },
    'pg.defter.riskLine': { tr: 'Kadran karar verir, sen değil.', en: 'The gauge decides, not you.' },
    'pg.defter.thAplus': { tr: 'A+ eşiği', en: 'A+ threshold' },
    'pg.defter.thB': { tr: 'B eşiği', en: 'B threshold' },
    'pg.defter.thMarked': { tr: 'İşaretli', en: 'Marked' },
    'pg.defter.fear': { tr: 'KORKU', en: 'FEAR' },
    'pg.defter.ecstasy': { tr: 'COŞKU', en: 'EUPHORIA' },
    'pg.defter.intentQ': { tr: 'Şu an neyi tradeliyorum?', en: 'What am I trading right now?' },
    'pg.defter.intentSetup': { tr: 'Setup\'ı', en: 'The setup' },
    'pg.defter.intentEmo': { tr: 'Duygumu', en: 'My emotion' },
    'pg.defter.sess': { tr: 'Seans', en: 'Session' },
    'pg.defter.strat': { tr: 'Strateji', en: 'Strategy' },
    'pg.defter.model': { tr: 'Entry Model', en: 'Entry Model' },
    'pg.defter.day': { tr: 'Gün', en: 'Day' },
    'pg.defter.catData': { tr: 'Veri Kriterleri', en: 'Data Criteria' },
    'pg.defter.catTech': { tr: 'Teknik Kriterler', en: 'Technical Criteria' },
    'pg.defter.senaryo': { tr: 'Senaryo · bunu ne bozar', en: 'Scenario · what invalidates it' },
    'pg.defter.senaryoPh': { tr: '2 cümle: beklediğim akış + invalidation.', en: '2 sentences: the flow I expect + invalidation.' },
    'pg.defter.catPos': { tr: 'Pozisyon Yönetimi', en: 'Position Management' },
    'pg.defter.anti': { tr: 'Anti senaryo · beni stop etmek isteyen senaryo', en: 'Anti-scenario · the scenario trying to stop me out' },
    'pg.defter.antiPh': { tr: 'Karşı taraf ne görüyor? Hangi akış gelirse stopum avlanır — likidite nerede, hangi seviyeye sweep gelir?', en: 'What does the other side see? Which flow would hunt my stop — where is the liquidity, which level gets swept?' },
    'pg.defter.inPos': { tr: 'Pozisyon Esnasında', en: 'While in Position' },
    'pg.defter.sentT': { tr: 'Piyasa Duyarlılığı', en: 'Market Sentiment' },
    'pg.defter.sentL': { tr: 'Çoğunluk LONG düşünüyor', en: 'Majority thinks LONG' },
    'pg.defter.sentS': { tr: 'Çoğunluk SHORT düşünüyor', en: 'Majority thinks SHORT' },
    'pg.defter.sentNote': { tr: 'Kalabalık nerede? Seçim yapmazsan skora etkisi yok.', en: 'Where is the crowd? If you don\'t choose, it doesn\'t affect the score.' },
    'pg.defter.eodT': { tr: 'Günlük Plan · Gün Sonu', en: 'Daily Plan · End of Day' },
    'pg.defter.eod': { tr: 'Gün sonu · plana uydu mu · saptıysam neden · yarın için tek düzeltme', en: 'End of day · did I follow the plan · if not, why · one fix for tomorrow' },
    'pg.defter.eodPh': { tr: 'Akşam doldurulur. İlk emir, sabah blokları dolmadan konmaz.', en: 'Fill in the evening. The first order is not placed until the morning sessions open.' },
    'pg.defter.savePlan': { tr: 'Planı İşle', en: 'Apply Plan' },
    'pg.defter.clear': { tr: 'Temizle', en: 'Clear' },
    'pg.defter.tradeDate': { tr: 'İşlem tarihi', en: 'Trade date' },
    'pg.defter.today': { tr: 'bugün', en: 'today' },
    'pg.defter.saveTrade': { tr: 'İşlemi Kaydet', en: 'Save Trade' },
    'pg.defter.share': { tr: 'Görsel Paylaş', en: 'Share Image' },
    'pg.defter.newTrade': { tr: 'Yeni İşlem', en: 'New Trade' },
    'pg.defter.editBook': { tr: 'Defteri Düzenle', en: 'Edit Journal' },
    'pg.defter.logT': { tr: 'İşlem Kaydı', en: 'Trade Log' },
    'pg.defter.fAll': { tr: 'Tümü', en: 'All' },
    'pg.defter.fToday': { tr: 'Bugün', en: 'Today' },
    'pg.defter.fWeek': { tr: 'Bu hafta', en: 'This week' },
    'pg.defter.fMonth': { tr: 'Bu ay', en: 'This month' },
    'pg.defter.fPair': { tr: 'Bu parite', en: 'This pair' },
    'pg.defter.export': { tr: 'Veriyi Dışa Aktar', en: 'Export Data' },
    'pg.defter.copy': { tr: 'Kopyala', en: 'Copy' },
    'pg.defter.exportNote': { tr: 'Tümünü kopyala ve analiz için Claude\'a yapıştır.', en: 'Copy everything and paste it to Claude for analysis.' },
    'pg.defter.anT': { tr: 'Kriter Analizi', en: 'Criteria Analysis' },
    'pg.data.t': { tr: 'Trade Günlüğü', en: 'Trade Journal' },
    'pg.data.s': { tr: 'İşlemlerini kaydet, kümülatif R eğrisini izle.', en: 'Log your trades and track the cumulative R curve.' },
    'pg.data.newTrade': { tr: '+ Yeni İşlem', en: '+ New Trade' },
    'pg.data.lDate': { tr: 'Tarih', en: 'Date' },
    'pg.data.lPair': { tr: 'Parite', en: 'Pair' },
    'pg.data.phPair': { tr: 'BTC, XAU…', en: 'BTC, XAU…' },
    'pg.data.lDir': { tr: 'Yön', en: 'Direction' },
    'pg.data.lR': { tr: 'R', en: 'R' },
    'pg.data.phR': { tr: '+2.5 / -0.3 — kayıp için (-) ile gir', en: '+2.5 / -0.3 — use (-) for losses' },
    'pg.data.lStrat': { tr: 'Strateji', en: 'Strategy' },
    'pg.data.phStrat': { tr: 'Breaker, FVG…', en: 'Breaker, FVG…' },
    'pg.data.lModel': { tr: 'Entry Model', en: 'Entry Model' },
    'pg.data.phModel': { tr: 'ör. H1 FVG + M15 iBOS', en: 'e.g. H1 FVG + M15 iBOS' },
    'pg.data.lNote': { tr: 'Not', en: 'Note' },
    'pg.data.phNote': { tr: 'İşlemle ilgili notların…', en: 'Notes about the trade…' },
    'pg.data.cSetup': { tr: 'Setup', en: 'Setup' },
    'pg.data.cEntry': { tr: 'Entry', en: 'Entry' },
    'pg.data.cExit': { tr: 'Exit', en: 'Exit' },
    'pg.data.cRisk': { tr: 'Risk', en: 'Risk' },
    'pg.data.cPsycho': { tr: 'Psikoloji', en: 'Psychology' },
    'pg.data.imgDrop': { tr: '📷 Resim sürükle/bırak veya Ctrl+V yapıştır', en: '📷 Drag & drop an image or press Ctrl+V' },
    'pg.data.importT': { tr: 'İçe Aktar', en: 'Import' },
    'pg.data.importDefter': { tr: 'Check List işlemlerini aktar', en: 'Import Check List trades' },
    'pg.data.pullNotion': { tr: '⬇ Notion\'dan çek', en: '⬇ Pull from Notion' },
    'pg.data.connectNotion': { tr: '🔗 Notion\'a Bağlan', en: '🔗 Connect to Notion' },
    'pg.data.csvBtn': { tr: 'CSV yükle (broker/MetaTrader)', en: 'Upload CSV (broker/MetaTrader)' },
    'pg.data.ndbSummary': { tr: '⚙ Notion Database Ayarları', en: '⚙ Notion Database Settings' },
    'pg.data.ndbKripto': { tr: 'Kripto DB ID', en: 'Crypto DB ID' },
    'pg.data.ndbFx': { tr: 'Fx DB ID', en: 'FX DB ID' },
    'pg.data.ndbWeek': { tr: 'Haftalık Değerlendirme DB ID', en: 'Weekly Review DB ID' },
    'pg.data.ndbWeekPh': { tr: 'Haftalık değerlendirme database id', en: 'Weekly review database id' },
    'pg.data.save': { tr: 'Kaydet', en: 'Save' },
    'pg.data.importHint': { tr: 'Alfa-Check List işlemleri R sonuçlarıyla buraya gelir. CSV: broker geçmişini yükle (date, symbol, type, profit).', en: 'Alfa-Check List trades come here with their R results. CSV: upload broker history (date, symbol, type, profit).' },
    'pg.data.allTrades': { tr: 'Tüm İşlemler', en: 'All Trades' },
    'pg.data.clearAll': { tr: 'Tümünü temizle', en: 'Clear all' },
    'pg.data.aiT': { tr: '🧠 Trading Coach — YZ Analiz', en: '🧠 Trading Coach — AI Analysis' },
    'pg.data.aiPh': { tr: 'İşlemlerini analiz etmek için bir filtre seç ve "Analiz Et" butonuna bas.<br>YZ; strateji bazında performans, varyans, notlarını ve genel trading kaliteni değerlendirir.', en: 'Select a filter and press "Analyze" to have your trades analyzed.<br>The AI evaluates strategy-based performance, variance, your notes and overall trading quality.' },
    'pg.data.aiAll': { tr: 'Tüm işlemleri analiz et', en: 'Analyze all trades' },
    'pg.data.aiWins': { tr: 'Sadece kazananları', en: 'Only winners' },
    'pg.data.aiLosses': { tr: 'Sadece kaybedenleri', en: 'Only losers' },
    'pg.data.aiRecent': { tr: 'Son 20 işlemi', en: 'Last 20 trades' },
    'pg.data.aiStrat': { tr: 'Strateji bazında karşılaştır', en: 'Compare by strategy' },
    'pg.data.aiBtn': { tr: '🎯 Analiz Et', en: '🎯 Analyze' },
    'pg.review.t': { tr: 'Haftalık Değerlendirme', en: 'Weekly Review' },
    'pg.review.s': { tr: 'Haftalık RR gir, kümülatif eğrini ve retrospektini izle.', en: 'Enter weekly RR and track your cumulative curve and retrospective.' },
    'pg.review.thisWeek': { tr: 'Bu hafta', en: 'This week' },
    'pg.review.week': { tr: 'Hafta', en: 'Week' },
    'pg.review.month': { tr: 'Ay Özeti', en: 'Month Summary' },
    'pg.review.nPush': { tr: '⬆ Notion\'a Senkronla', en: '⬆ Sync to Notion' },
    'pg.review.nPull': { tr: '⬇ Notion\'dan Çek', en: '⬇ Pull from Notion' },
    'pg.review.totalRR': { tr: 'Toplam RR', en: 'Total RR' },
    'pg.review.kripto': { tr: 'Kripto', en: 'Crypto' },
    'pg.review.fx': { tr: 'FX', en: 'FX' },
    'pg.review.empty': { tr: 'Haftalık RR girdikçe kümülatif eğri burada oluşur.', en: 'The cumulative curve builds here as you enter weekly RR.' },
    'pg.review.eqT': { tr: '📈 Trade Günlüğü Kümülatif PnL (R)', en: '📈 Trade Journal Cumulative PnL (R)' },
    'pg.review.addSection': { tr: '+ Bölüm ekle', en: '+ Add section' },
    'pg.review.metricsT': { tr: 'Bu Hafta — Ölçütler', en: 'This Week — Metrics' },
    'pg.review.addMetric': { tr: '+ Ölçüt', en: '+ Metric' },
    'pg.news.t': { tr: 'AlfaNews', en: 'AlfaNews' },
    'pg.news.s': { tr: 'Dergi formatında analist içerikleri ve piyasa içgörüleri.', en: 'Analyst content and market insights in magazine format.' },
    'pg.news.editMode': { tr: 'Düzenleme modu', en: 'Edit mode' },
    'pg.news.preview': { tr: '👁 Okuyucu önizleme', en: '👁 Reader preview' },
    'pg.news.authors': { tr: 'Analistler', en: 'Analysts' },
    'pg.news.addEntry': { tr: '＋ Analiz ekle', en: '＋ Add analysis' },
    'pg.news.backEdit': { tr: '✏ Düzenlemeye dön', en: '✏ Back to editing' },
    'pg.news.hint': { tr: 'Çevir: kaydır · oklar · klavye · içindekiler · Görsele tıkla → büyüt', en: 'Navigate: scroll · arrows · keyboard · table of contents · Click image → zoom' },
    'pg.news.addUpdate': { tr: '↺ Güncelleme ekle', en: '↺ Add update' },
    'pg.news.cta': { tr: '🔗 Yönlendirme', en: '🔗 Redirect' },
    'pg.news.upd': { tr: 'Güncelleme', en: 'Update' },
    'pg.news.an': { tr: 'Analiz', en: 'Analysis' },
    'pg.news.toAnalysis': { tr: '← Ana analize git', en: '← Go to original analysis' },
    'pg.news.before': { tr: 'ÖNCE · ANALİZ', en: 'BEFORE · ANALYSIS' },
    'pg.news.after': { tr: 'SONRA · SONUÇ', en: 'AFTER · RESULT' },
    'pg.news.result': { tr: '📊 SONUÇ', en: '📊 RESULT' },
    'pg.news.viewSite': { tr: 'Sitede Gör', en: 'View on Site' },
    'pg.news.share': { tr: '🔗 Analizi Paylaş', en: '🔗 Share Analysis' },
    'pg.news.shareCopied': { tr: 'Analiz bağlantısı kopyalandı ✓', en: 'Analysis link copied ✓' },
    'pg.news.updates': { tr: 'Güncellemeler', en: 'Updates' },
    'pg.news.updFor': { tr: 'Bu analize güncelleme ekle', en: 'Add update to this analysis' },
    'pg.news.pasteHint': { tr: '📋 Görseli yapıştır (Ctrl+V) · tıkla · sürükle', en: '📋 Paste image (Ctrl+V) · click · drag' },
    'pg.news.autoBefore': { tr: 'bağlı analizden otomatik', en: 'auto from linked analysis' },
    'pg.news.pin': { tr: 'Sabitle', en: 'Pin' },
    'pg.news.pinTitle': { tr: 'Bu görseli sabitle — bağlı analiz değişirse aynı kalır', en: 'Pin this image — stays fixed even if the linked analysis changes' },
    'pg.news.convert': { tr: 'Analize çevir', en: 'Convert to analysis' },
    'pg.news.convertTitle': { tr: 'Güncellemeyi bağımsız bir analiz sayfasına çevir', en: 'Turn this update into a standalone analysis page' },
    'pg.news.cardImg': { tr: 'Kart görseli', en: 'Card image' },
    'pg.news.cardImgTitle': { tr: 'Before/After önizleme kartını büyük aç (sürükle ya da indir)', en: 'Open the before/after preview card large (drag or download)' },
    'pg.news.cardImgEmpty': { tr: 'Kart için en az bir görsel gerekli', en: 'At least one image is needed for the card' },
    'pg.news.cardDownload': { tr: 'İndir', en: 'Download' },
    'pg.news.cardClose': { tr: 'Kapat', en: 'Close' },
    'pg.news.cardHint': { tr: 'Görseli sürükleyin ya da sağ tıklayıp kopyalayın', en: 'Drag the image or right-click to copy' },
    'pg.egitim.t': { tr: 'Alfa Edu', en: 'Alfa Edu' },
    'pg.egitim.s': { tr: 'Eğitsel trader kanalları — videolar, notlar ve fotoğraflar. Kanalına tıkla, içeriği izle.', en: 'Educational trader channels — videos, notes and photos. Click a channel to watch its content.' },
    'pg.egitim.lvl1': { tr: 'Temel', en: 'Basic' },
    'pg.egitim.lvl2': { tr: 'Orta', en: 'Intermediate' },
    'pg.egitim.lvl3': { tr: 'İleri', en: 'Advanced' },
    'pg.egitim.lvlAll': { tr: 'Tümü', en: 'All' },
    'pg.egitim.empty': { tr: 'Bu bölümde konu yok. &quot;+ Konu&quot; ile ekle.', en: 'No topics in this section. Add one with &quot;+ Topic&quot;.' },
    'pg.egitim.openYt': { tr: 'YouTube\'da aç ↗', en: 'Open on YouTube ↗' },
    'pg.egitim.cheer': { tr: 'Tebrikler! 🎉', en: 'Congratulations! 🎉' },
    'pg.egitim.watched': { tr: 'İzledim', en: 'Watched' },
    'pg.egitim.videos': { tr: 'İçerik', en: 'Content' },
    'pg.egitim.addVideo': { tr: '+ Video ekle', en: '+ Add video' },
    'pg.egitim.notes': { tr: 'Konu notların', en: 'Your topic notes' },
    'pg.egitim.notesPh': { tr: 'Kısa not: çıkarımlar, dakikalar, tekrar izlenecek yerler…', en: 'Quick note: takeaways, timestamps, parts to rewatch…' },
    'pg.egitim.playerEmpty': { tr: 'Soldan bir konu seç — videoları burada büyük ekranda açılsın.', en: 'Select a topic on the left — watch the videos here on the big screen.' },
    'pg.egitim.new': { tr: 'Yeni', en: 'New' },
    'pg.egitim.titlePh': { tr: 'Başlık', en: 'Title' },
    'pg.egitim.urlPh': { tr: 'YouTube video ya da oynatma listesi bağlantısı', en: 'YouTube video or playlist link' },
    'pg.egitim.level': { tr: 'Seviye', en: 'Level' },
    'pg.egitim.editTopic': { tr: 'Konu başlığını düzenle', en: 'Edit topic title' },
    'pg.egitim.channels': { tr: '🎬 Eğitsel Kanal — Traderlar', en: '🎬 Edu Channel — Traders' },
    'pg.egitim.chPick': { tr: 'Bir trader kanalına tıkla — videoları ve notları burada izle.', en: 'Pick a trader channel — watch videos and notes here.' },
    'pg.egitim.chEmpty': { tr: 'Henüz trader kanalı yok.', en: 'No trader channel yet.' },
    'pg.egitim.chAdd': { tr: '＋ Yeni kanal ekle', en: '＋ Add new channel' },
    'pg.egitim.chEditProf': { tr: '✎ Profili düzenle', en: '✎ Edit profile' },
    'pg.egitim.chBack': { tr: '← Alfa Edu', en: '← Alfa Edu' },
    'pg.egitim.chNoTopics': { tr: 'Bu kanalda henüz konu yok.', en: 'No topics in this channel yet.' },
    'pg.egitim.chProfT': { tr: 'Kanal Profili', en: 'Channel Profile' },
    'pg.egitim.chNamePh': { tr: 'Trader adı / kanal adı', en: 'Trader / channel name' },
    'pg.egitim.chBioPh': { tr: 'Kısa tanıtım — ne paylaşacaksın?', en: 'Short intro — what will you share?' },
    'pg.egitim.chEditors': { tr: 'Düzenleyebilen mailler (virgülle)', en: 'Editor emails (comma separated)' },
    'pg.egitim.chEditorsPh': { tr: 'ornek@mail.com, diger@mail.com', en: 'name@mail.com, other@mail.com' },
    'pg.egitim.chDel': { tr: 'Kanalı sil', en: 'Delete channel' },
    'pg.egitim.addContent': { tr: '+ İçerik ekle', en: '+ Add content' },
    'pg.egitim.typeVideo': { tr: '🎬 Video', en: '🎬 Video' },
    'pg.egitim.typeArticle': { tr: '📄 Makale', en: '📄 Article' },
    'pg.egitim.typePost': { tr: '💬 Gönderi', en: '💬 Post' },
    'pg.egitim.typeNot': { tr: '📝 Not', en: '📝 Note' },
    'pg.egitim.typeFoto': { tr: '📷 Foto', en: '📷 Photo' },
    'pg.egitim.bodyPh': { tr: 'İçeriğin… (# başlık, - madde, **kalın** destekli)', en: 'Your content… (# heading, - bullet, **bold** supported)' },
    'pg.mentoring.t': { tr: 'Mentoring', en: 'Mentoring' },
    'pg.mentoring.s': { tr: 'Ahmet + Çağatay ortak eğitim paneli — konular, notlar ve fotoğraflar otomatik senkronlanır.', en: 'Ahmet + Çağatay shared training panel — topics, notes and photos sync automatically.' },
    'pg.mentoring.empty': { tr: 'Henüz konu yok. &quot;+ Konu&quot; ile başla.', en: 'No topics yet. Start with &quot;+ Topic&quot;.' },
    'pg.mentoring.select': { tr: 'Soldan bir konu seç — notları ve fotoğrafları burada gör.', en: 'Select a topic on the left — see its notes and photos here.' },
    'pg.indicators.t': { tr: 'İndikatörler', en: 'Indicators' },
    'pg.indicators.s': { tr: 'Aggr Trade Workspace · Alfa Levels · Flow — açıklama, örnek, video, backtest', en: 'Aggr Trade Workspace · Alfa Levels · Flow — explanation, example, video, backtest' },
    'pg.onchain.t': { tr: 'Onchain Verileri', en: 'Onchain Data' },
    'pg.onchain.s': { tr: 'Coinglass Supercharts — Funding / CVD / OI', en: 'Coinglass Supercharts — Funding / CVD / OI' },
    'pg.onchain.newTab': { tr: 'Yeni Sekmede Aç ↗', en: 'Open in New Tab ↗' },
    'pg.onchain.blocked': { tr: 'Bu site iframe\'i engelliyor. Yeni sekmede açın:', en: 'This site blocks iframes. Open it in a new tab:' },
    'pg.onchain.open': { tr: 'Aç ↗', en: 'Open ↗' },
    'pg.cal.t': { tr: 'Ekonomik Takvim', en: 'Economic Calendar' },
    'pg.cal.s': { tr: '3 yıldız haberler — yüksek etkili makro verileri ve merkez bankası kararları', en: '3-star news — high-impact macro data and central bank decisions' },
    'pg.cal.highImpact': { tr: 'Yüksek etki', en: 'High impact' },
    'pg.cal.all': { tr: 'Tümü', en: 'All' },
    'pg.cal.refresh': { tr: '🔄 Yenile', en: '🔄 Refresh' },
    'pg.chat.t': { tr: 'Canlı Destek', en: 'Live Support' },
    'pg.chat.s': { tr: 'Ziyaretçilerden gelen mesajları gör, yanıtla. Yanıtların anında kullanıcının sohbetinde görünür.', en: 'See and reply to messages from visitors. Your replies appear instantly in the user\'s chat.' },
    'pg.chat.empty': { tr: 'Soldan bir konuşma seç', en: 'Select a conversation on the left' },
    'pg.chat.replyPh': { tr: 'Yanıtını yaz...', en: 'Type your reply...' },
    'pg.calc.t': { tr: 'Alfa Calculator', en: 'Alfa Calculator' },
    'pg.calc.s': { tr: 'FX risk ve pozisyon boyutu hesaplayıcı', en: 'FX risk and position size calculator' },
    'pg.calc.h2': { tr: 'FX Risk & Pozisyon Boyutu Hesaplayıcı', en: 'FX Risk & Position Size Calculator' },
    'pg.calc.acct': { tr: 'Hesap Bilgileri', en: 'Account Info' },
    'pg.calc.balance': { tr: 'Hesap Bakiyesi ($)', en: 'Account Balance ($)' },
    'pg.calc.riskType': { tr: 'Risk Türü', en: 'Risk Type' },
    'pg.calc.riskPct': { tr: 'Risk Oranı (%)', en: 'Risk Percentage (%)' },
    'pg.calc.riskAmt': { tr: 'Risk Miktarı ($)', en: 'Risk Amount ($)' },
    'pg.calc.trade': { tr: 'İşlem Bilgileri', en: 'Trade Info' },
    'pg.calc.instr': { tr: 'Parite / Enstrüman', en: 'Pair / Instrument' },
    'pg.calc.entry': { tr: 'Giriş Fiyatı (Entry)', en: 'Entry Price' },
    'pg.calc.sl': { tr: 'Stop-Loss Fiyatı (SL)', en: 'Stop-Loss Price (SL)' },
    'pg.calc.lev': { tr: 'Kaldıraç (Leverage)', en: 'Leverage' },
    'pg.calc.results': { tr: 'Hesaplama Sonuçları', en: 'Calculation Results' },
    'pg.calc.rRiskAmt': { tr: 'Risk Edilen Tutar:', en: 'Amount at Risk:' },
    'pg.calc.rRiskDist': { tr: 'Risk Edilen Mesafe:', en: 'Distance at Risk:' },
    'pg.calc.rStdLot': { tr: 'Standard Lot:', en: 'Standard Lot:' },
    'pg.calc.rMiniLot': { tr: 'Mini Lot (0.1):', en: 'Mini Lot (0.1):' },
    'pg.calc.rMicroLot': { tr: 'Mikro Lot (0.01):', en: 'Micro Lot (0.01):' },
    'pg.calc.rNotional': { tr: 'Pozisyon Büyüklüğü:', en: 'Position Size:' },
    'pg.calc.rMargin': { tr: 'Gerekli Marj:', en: 'Required Margin:' },
    'pg.calc.rPipVal': { tr: '1 Pip Değeri (1 Lot):', en: 'Pip Value (1 Lot):' },
    'pg.bas.t': { tr: 'Alfa Ol', en: 'Become Alfa' },
    'pg.bas.hero': { tr: 'Junior ya da Senior — aktif, paylaşan, gelişime açık trader\'ları arıyoruz.', en: 'Junior or Senior — we are looking for active, sharing, growth-minded traders.' },
    'pg.bas.pnl': { tr: 'Topluluk Kümülatif PnL', en: 'Community Cumulative PnL' },
    'pg.bas.pnlSub': { tr: 'Ocak – Temmuz 2026 · toplam R', en: 'January – July 2026 · total R' },
    'pg.bas.junT': { tr: 'Junior Alfa Trader', en: 'Junior Alfa Trader' },
    'pg.bas.junS': { tr: 'Bu yola başlıyorsun. Sende aradıklarımız: aktiflik, chart paylaşımı ve gelişime açıklık. Karşılığında sana işlemleri, mentörlüğü ve sohbet ortamını sunuyoruz.', en: 'You are starting this path. What we look for in you: activity, chart sharing and openness to growth. In return we give you trades, mentorship and a chat community.' },
    'pg.bas.bybit': { tr: 'Bybit ile Katıl', en: 'Join with Bybit' },
    'pg.bas.okx': { tr: 'OKX ile Katıl', en: 'Join with OKX' },
    'pg.bas.uidHint': { tr: 'Kaydoldun mu? UID\'ni gir, topluluğa katıl.', en: 'Signed up? Enter your UID to join the community.' },
    'pg.bas.uidPh': { tr: 'Bybit / OKX UID\'n', en: 'Your Bybit / OKX UID' },
    'pg.bas.join': { tr: 'Katıl', en: 'Join' },
    'pg.bas.senT': { tr: 'Senior Alfa Trader', en: 'Senior Alfa Trader' },
    'pg.bas.senS': { tr: 'Deneyimli trader burada yerini alıyor. Sende aradıklarımız: verify başarı, before/after tool ile işlem ve grup içi görevlendirmelere katılım. Karşılığında ekip işlemleri, mentörlük ve sohbet ortamı.', en: 'The experienced trader takes their place here. What we look for in you: verified success, trading with the before/after tool and participation in group assignments. In return: team trades, mentorship and a chat community.' },
    'pg.bas.fName': { tr: 'Adın / Nick', en: 'Your name / Nick' },
    'pg.bas.fTg': { tr: 'Telegram kullanıcı adın', en: 'Your Telegram username' },
    'pg.bas.fX': { tr: 'X hesabın (opsiyonel)', en: 'Your X account (optional)' },
    'pg.bas.fExp': { tr: 'Tecrübe', en: 'Experience' },
    'pg.bas.fMarket': { tr: 'Piyasa', en: 'Market' },
    'pg.bas.fFreq': { tr: 'Sıklık', en: 'Frequency' },
    'pg.bas.fMethod': { tr: 'Analiz', en: 'Analysis' },
    'pg.bas.fLevel': { tr: 'Seviye', en: 'Level' },
    'pg.bas.fPnl': { tr: 'Son 6 ay', en: 'Last 6 months' },
    'pg.bas.fPnl2': { tr: '2 aylık PnL screenshot linki', en: '2-month PnL screenshot link' },
    'pg.bas.fPayout': { tr: 'Son 2 payout fotoğraf linki', en: 'Last 2 payout photo links' },
    'pg.bas.fLast': { tr: 'Son işlem TradingView linki', en: 'Last trade TradingView link' },
    'pg.bas.fWhy': { tr: 'Neden Alfa Traders\'a katılmak istiyorsun?', en: 'Why do you want to join Alfa Traders?' },
    'pg.bas.fSubmit': { tr: 'Başvur →', en: 'Apply →' },
    'pg.pano.room': { tr: 'Oda adı', en: 'Room name' },
    'pg.pano.drag': { tr: 'Sürükle ve taşı', en: 'Drag to move' },
    'pg.pano.openRoom': { tr: 'Odayı Aç', en: 'Open Room' },
    'pg.pano.hint': { tr: 'Sürükle = çiz / Ctrl+sürükle = seç / Boşluk+sürükle = kaydır / Tekerlek = yakınlaştır / F = dolu / Ctrl+V = görsel / Sil = Delete', en: 'Drag = draw / Ctrl+drag = select / Space+drag = pan / Wheel = zoom / F = fill / Ctrl+V = image / Delete = delete' },
    'pg.pano.tSelect': { tr: 'Seç / Taşı (V)', en: 'Select / Move (V)' },
    'pg.pano.tPen': { tr: 'Kalem (P)', en: 'Pen (P)' },
    'pg.pano.tLine': { tr: 'Çizgi (L)', en: 'Line (L)' },
    'pg.pano.tRect': { tr: 'Dikdörtgen (R)', en: 'Rectangle (R)' },
    'pg.pano.tEllipse': { tr: 'Elips (O)', en: 'Ellipse (O)' },
    'pg.pano.tText': { tr: 'Metin (T)', en: 'Text (T)' },
    'pg.pano.tEraser': { tr: 'Silgi (E)', en: 'Eraser (E)' },
    'pg.pano.tHand': { tr: 'Kaydır (H)', en: 'Pan (H)' },
    'pg.pano.color': { tr: 'Renk', en: 'Color' },
    'pg.pano.size': { tr: 'Kalınlık', en: 'Thickness' },
    'pg.pano.thin': { tr: 'İnce', en: 'Thin' },
    'pg.pano.med': { tr: 'Orta', en: 'Medium' },
    'pg.pano.thick': { tr: 'Kalın', en: 'Thick' },
    'pg.pano.undo': { tr: 'Geri al (Ctrl+Z)', en: 'Undo (Ctrl+Z)' },
    'pg.pano.redo': { tr: 'Yinele (Ctrl+Y)', en: 'Redo (Ctrl+Y)' },
    'pg.pano.dup': { tr: 'Çoğalt (Ctrl+D)', en: 'Duplicate (Ctrl+D)' },
    'pg.pano.del': { tr: 'Sil (Delete)', en: 'Delete (Delete)' },
    'pg.pano.fill': { tr: 'İçi dolu şekiller (F)', en: 'Filled shapes (F)' },
    'pg.pano.img': { tr: 'Görsel ekle / yapıştır (Ctrl+V)', en: 'Add / paste image (Ctrl+V)' },
    'pg.pano.fs': { tr: 'Tam ekran', en: 'Fullscreen' },
    'pg.pano.zout': { tr: 'Uzaklaştır', en: 'Zoom out' },
    'pg.pano.zin': { tr: 'Yakınlaştır', en: 'Zoom in' },
    'pg.pano.zfit': { tr: 'Sığdır', en: 'Fit' },
    'pg.pano.clear': { tr: 'Temizle', en: 'Clear' },
    'hm.sub': { tr: 'Trader\'lar için disiplin, analiz ve öğrenme platformu', en: 'A discipline, analysis and learning platform for traders' },
    'hm.c1.t': { tr: '🎯 Alfa-Check List', en: '🎯 Alfa-Check List' },
    'hm.c1.s': { tr: 'İşlem öncesi kriterleri puanla, A+ / B kararını al.', en: 'Score the pre-trade criteria and get your A+ / B decision.' },
    'hm.c2.t': { tr: '📓 Trade Günlüğü', en: '📓 Trade Journal' },
    'hm.c2.s': { tr: 'Notion senkronu + kümülatif R eğrisi, CSV içe aktarma.', en: 'Notion sync + cumulative R curve, CSV import.' },
    'hm.c3.t': { tr: '📈 Haftalık Değerlendirme', en: '📈 Weekly Review' },
    'hm.c3.s': { tr: 'Haftalık RR gir, trendini ve retrospektini izle.', en: 'Enter weekly RR, track your trend and retrospective.' },
    'hm.c4.t': { tr: '🎓 Alfa Edu', en: '🎓 Alfa Edu' },
    'hm.c4.s': { tr: 'Teknikten psikolojiye, bölüm → konu → video eğitim.', en: 'From technicals to psychology, section → topic → video learning.' },
    'hm.c5.t': { tr: '📊 İndikatörler', en: '📊 Indicators' },
    'hm.c5.s': { tr: 'Aggr Trade, Alfa Levels ve Flow — kurulum & kullanım.', en: 'Aggr Trade, Alfa Levels and Flow — setup & usage.' },
    'hm.c6.t': { tr: '⛓️ Onchain Verileri', en: '⛓️ Onchain Data' },
    'hm.c6.s': { tr: 'Coinglass funding, CVD ve open interest tek ekranda.', en: 'Coinglass funding, CVD and open interest on one screen.' },
    'hm.c7.t': { tr: '📰 AlfaNews', en: '📰 AlfaNews' },
    'hm.c7.s': { tr: 'Dergi formatında analist içerikleri ve piyasa analizleri.', en: 'Analyst content and market analyses in magazine format.' },
    'hm.c8.t': { tr: '📅 Ekonomik Takvim', en: '📅 Economic Calendar' },
    'hm.c8.s': { tr: '3 yıldızlı yüksek etkili makro haberleri kaçırma.', en: 'Don\'t miss 3-star high-impact macro news.' },
    'hm.c9.t': { tr: '🤝 Alfa Ol', en: '🤝 Become Alfa' },
    'hm.c9.s': { tr: 'Topluluk akışı, PnL performansı, referansla katıl.', en: 'Community feed, PnL performance, join by referral.' },
    'hm.tips': { tr: '💡 Verimli Kullanım İpuçları', en: '💡 Tips for Efficient Use' },
    'hm.tips.1': { tr: '<strong>Alfa-Check List</strong> — Her işlem öncesi pair\'ini seç, kriterleri puanla. Eşikler otomatik karar versin. Seans kalitesini gir, günlük plan yap.', en: '<strong>Alfa-Check List</strong> — Pick your pair before every trade and score the criteria. Let the thresholds decide automatically. Log session quality and make a daily plan.' },
    'hm.tips.2': { tr: '<strong>Trade Günlüğü</strong> — İşlem sonrası R değerini gir. Notion\'a bağlanıp otomatik çek. CSV yükleme ile broker geçmişini içe aktar. Kümülatif eğriyi takip et.', en: '<strong>Trade Journal</strong> — Enter the R value after each trade. Connect to Notion and pull automatically. Import broker history via CSV. Track the cumulative curve.' },
    'hm.tips.3': { tr: '<strong>Haftalık Değerlendirme</strong> — Her hafta kripto/fx RR\'yi gir. Değerlendirme bölümleri ekle, ölçütler belirle. trendini izle.', en: '<strong>Weekly Review</strong> — Enter your crypto/FX RR every week. Add review sections, set metrics, track your trend.' },
    'hm.tips.4': { tr: '<strong>Alfa Edu</strong> — Bölüm seç (Teknik Analiz\'de Temel/Orta/İleri seviye filtresi var), konu aç, video ekle. İzledim işaretle.', en: '<strong>Alfa Edu</strong> — Pick a section (Technical Analysis has a Basic/Intermediate/Advanced filter), open a topic, add videos. Mark as watched.' },
    'hm.tips.5': { tr: '<strong>Onchain</strong> — Coinglass Supercharts tek sayfada. Onchain Analizi eğitim bölümü de eklendi.', en: '<strong>Onchain</strong> — Coinglass Supercharts on one page. An Onchain Analysis education section was added too.' },
    'hm.tips.6': { tr: '<strong>Notion Senkronu</strong> — "Notion\'a Bağlan" ile OAuth yap, database ID\'lerini ayarlardan gir. Tek tuşla trade\'lerini çek.', en: '<strong>Notion Sync</strong> — Do OAuth with "Connect to Notion", enter the database IDs in settings. Pull your trades with one click.' },
    'hm.rv.t': { tr: '⭐ Üyeler ne diyor?', en: '⭐ What do members say?' },
    'hm.rv.s': { tr: 'Siteyi beğendin mi? Deneyimini paylaş, yeni trader\'lara yol göster.', en: 'Like the site? Share your experience and guide new traders.' },
    'hm.rv.more': { tr: 'Daha fazla yorum gör ↓', en: 'See more reviews ↓' },
    'hs.h': { tr: '🎯 Sana daha iyi yardımcı olabilmemiz için', en: '🎯 To help you better' },
    'hs.p': { tr: '30 saniye — neye ihtiyacın olduğunu söyle, biz ona göre içerik hazırlayalım.', en: '30 seconds — tell us what you need and we\'ll tailor the content.' },
    'hs.skip': { tr: 'Şimdi değil ✕', en: 'Not now ✕' },
    'hs.skipAria': { tr: 'Kapat', en: 'Close' },
    'hs.q1': { tr: 'En çok nerede zorlanıyorsun?', en: 'Where do you struggle the most?' },
    'hs.q1.o1': { tr: 'Disiplin', en: 'Discipline' },
    'hs.q1.o2': { tr: 'Risk yönetimi', en: 'Risk management' },
    'hs.q1.o3': { tr: 'Teknik analiz', en: 'Technical analysis' },
    'hs.q1.o4': { tr: 'Psikoloji', en: 'Psychology' },
    'hs.q1.o5': { tr: 'Strateji', en: 'Strategy' },
    'hs.q2': { tr: 'Ne kadar zamandır trade yapıyorsun?', en: 'How long have you been trading?' },
    'hs.q2.o1': { tr: 'Yeni başladım', en: 'Just started' },
    'hs.q2.o2': { tr: '1-3 yıl', en: '1-3 years' },
    'hs.q2.o3': { tr: '3+ yıl', en: '3+ years' },
    'hs.q3': { tr: 'Hangi piyasada işlem yapıyorsun?', en: 'Which market do you trade?' },
    'hs.q3.o1': { tr: 'Kripto', en: 'Crypto' },
    'hs.q3.o2': { tr: 'FX', en: 'FX' },
    'hs.q3.o3': { tr: 'Hisse', en: 'Stocks' },
    'hs.q4': { tr: 'Şu an en çok ne arıyorsun?', en: 'What are you looking for most right now?' },
    'hs.q4.o1': { tr: 'Eğitim', en: 'Education' },
    'hs.q4.o2': { tr: 'Topluluk', en: 'Community' },
    'hs.q4.o3': { tr: 'Araçlar', en: 'Tools' },
    'hs.q4.o4': { tr: 'Mentorluk', en: 'Mentorship' },
    'hs.send': { tr: 'Gönder', en: 'Send' },
    'hs.hint': { tr: 'Tüm soruları yanıtla', en: 'Answer all questions' },
    'hs.done.t': { tr: 'Teşekkürler!', en: 'Thank you!' },
    'hs.done.msg': { tr: 'Cevaplarına göre sana en uygun bölümleri öneriyoruz.', en: 'We recommend the best sections for you based on your answers.' },
    'pg.bas.errConn': { tr: 'Sistem bağlantısı hazır değil.', en: 'System connection is not ready.' },
    'pg.bas.okJunior': { tr: '✅ Başvurun alındı! Seninle iletişime geçeceğiz.', en: '✅ Application received! We will reach out.' },
    'pg.bas.errRetry': { tr: 'Hata oluştu, tekrar dene.', en: 'An error occurred, try again.' },
    'pg.bas.okSenior': { tr: '✅ Başvurun alındı! Seni takip edeceğiz.', en: '✅ Application received! We will reach out.' },
    'pg.defter.aiEmptyProfile': { tr: 'En az strateji, duygusal zayıflık ya da problem seç — boş profil öneriyi anlamsızlaştırır.', en: 'Pick at least a strategy, emotional weakness or problem — an empty profile makes the suggestion meaningless.' },
    'chat.t': { tr: 'Alfa Destek', en: 'Alfa Support' },
    'chat.ph': { tr: 'Mesajını yaz...', en: 'Type your message...' },
    'chat.clear': { tr: 'Sohbeti Temizle', en: 'Clear Chat' },
    'chat.clearT': { tr: 'Sohbeti temizle', en: 'Clear chat' },
    'chat.live': { tr: 'Canlı Destek', en: 'Live Support' },
    'chat.thinking': { tr: '🤖 Düşünüyorum…', en: '🤖 Thinking…' },
    'pg.chat.noMsgs': { tr: 'Henüz mesaj yok.', en: 'No messages yet.' }
  };
  var saved = 'tr';
  try { saved = localStorage.getItem('alfa-lang') || 'tr'; } catch (e) {}
  if (saved !== 'tr' && saved !== 'en') saved = 'tr';
  window.LANG = saved;
  window.t = function (k) {
    var e = I18N[k];
    return e ? (e[window.LANG] !== undefined ? e[window.LANG] : e.tr) : k;
  };
  window.applyI18n = function () {
    var q = document.querySelectorAll.bind(document);
    q('[data-i18n]').forEach(function (el) { el.textContent = t(el.getAttribute('data-i18n')); });
    q('[data-i18n-html]').forEach(function (el) { el.innerHTML = t(el.getAttribute('data-i18n-html')); });
    q('[data-i18n-ph]').forEach(function (el) { el.setAttribute('placeholder', t(el.getAttribute('data-i18n-ph'))); });
    q('[data-i18n-aria]').forEach(function (el) { el.setAttribute('aria-label', t(el.getAttribute('data-i18n-aria'))); });
    q('[data-i18n-title]').forEach(function (el) { el.setAttribute('title', t(el.getAttribute('data-i18n-title'))); });
    q('#lang-btn,#lang-btn-app').forEach(function (el) { el.textContent = t('nav.lang'); });
    document.documentElement.setAttribute('lang', window.LANG === 'tr' ? 'tr' : 'en');
    if (typeof refreshRvStatic === 'function') refreshRvStatic();
  };
  window.setLang = function (l) {
    window.LANG = (l === 'en') ? 'en' : 'tr';
    try { localStorage.setItem('alfa-lang', window.LANG); } catch (e) {}
    applyI18n();
    try { if (typeof refreshRvDynamic === 'function') refreshRvDynamic(); } catch (e) {}
    try { if (typeof showDailyQuote === 'function') showDailyQuote(); } catch (e) {}
  };
  applyI18n();
  ['lang-btn', 'lang-btn-app'].forEach(function (id) {
    var b = document.getElementById(id);
    if (b) b.addEventListener('click', function () { setLang(window.LANG === 'tr' ? 'en' : 'tr'); });
  });
})();